- .idea/workspace.xml
- app/Http/Controllers/PostController.php
- resources/views/posts/formulario_crear_post.blade.php
- resources/views/posts/formulario_editar_post.blade.php
he cambiado el input del file al subir y editar post
> cambiando input del file

- .idea/workspace.xml
- app/Http/Controllers/PostController.php
- resources/views/home.blade.php
- resources/views/posts/_cards.blade.php
he retocado el script del scroll infinito
y he añadido el return del delete en postController
> retoques en scroll home y delete post

- app/Http/Controllers/PostController.php
- public/css/app.css
- resources/views/posts/_comment.blade.php
- resources/views/posts/detail.blade.php
- colores y estilo en el detalle de los posts.
> Colores y estilo en el detalle de post

- public/css/app.css
- resources/views/auth/login.blade.php
- resources/views/auth/register.blade.php
- resources/views/layouts/app.blade.php
- resources/views/posts/_discover.blade.php
- arreglado el estilo de loading papaya
> arreglado estilo de loading papaya

- .idea/dataSources/09c24a74-29e5-44de-b2f1-912021688134.xml
- .idea/workspace.xml
- resources/views/home.blade.php
- resources/views/posts/formulario_crear_post.blade.php
he cambiado la variable spinner y he puesto la consulta js directamente
> retoque funcion spiner

- .idea/workspace.xml
- app/Http/Controllers/PostController.php
- resources/views/posts/formulario_editar_post.blade.php
he editado la funcion de crearPost para que se creen carpetas personales donde se guardaran los archivos por usuario
> carpetas personales de cada usuario

- app/Http/Controllers/ProfileController.php
- resources/views/layouts/app.blade.php
- resources/views/posts/_cards.blade.php
- resources/views/posts/detail.blade.php
- resources/views/profiles/profile.blade.php
- routes/web.php
He creado el perfil de usuario con una maquetación bastante mejorable.
> Crear perfil usuario

- resources/views/posts/_cards.blade.php
- arreglo de la vista `_cards`
> arreglo de expected-end-of-file

- public/css/app.css
- resources/views/errors/403.blade.php
- resources/views/errors/404.blade.php
- resources/views/errors/419.blade.php
- resources/views/errors/500.blade.php
- estilo de las vistas `400`y `500`
> Estilo vistas 400 y 500

- public/css/app.css
- resources/views/layouts/app.blade.php
- resources/views/profiles/profile.blade.php
> Estilo del perfil de usuario

- app/Http/Controllers/ProfileController.php
- resources/views/profiles/profile.blade.php
- routes/web.php
Funciona pero faltará cambiar el locale del auth
> Actualizar contraseña

- .idea/Papaya.iml
- .idea/php.xml
- .idea/workspace.xml
- resources/views/auth/register.blade.php
- resources/views/home.blade.php
he retocado la vista de registro pra que el texto de noEmail salga en medio
he editado el home para que el spinner no se quede pillado cuando solo hay un post
> retoque spinner y vista registro

- app/Http/Controllers/ProfileController.php
- resources/views/posts/_cards.blade.php
- resources/views/posts/detail.blade.php
- resources/views/profiles/profile.blade.php
- routes/web.php
Permite editar la foto de perfil desde el perfil de usuario clickando sobre la imagen. 
Además he actualizado las vistas para que muestren la foto de perfil si se ha editado y, sino, la predeterminada.
> Editar foto perfil

- .idea/workspace.xml
- resources/views/auth/register.blade.php
he retocado el estilo el texto de "no se requiere email" para que sea responsive
> texto email registro responsive

- .idea/workspace.xml
- app/Http/Controllers/HomeController.php
- app/Post.php
- app/User.php
- resources/views/layouts/app.blade.php
- resources/views/profiles/profile.blade.php
he mejorado añadido al buscador la función de buscar por usuario
he puesto en funcionamiento el buscador de posts del perfil
> Search posts

- .idea/workspace.xml
- resources/views/profiles/profile.blade.php
> retoque responsive perfil otros

- app/Http/Controllers/Auth/RegisterController.php
He modificado la función de registro para que el primer usuario que cree una cuenta sea automáticamente el admin.
> Hacer que el primer usuario sea admin

- .idea/workspace.xml
- resources/views/profiles/profile.blade.php
he puesto width a la foto de perfil porque se veia muy pequeña
> retoque responsive foto perfil

- app/User.php
- config/mail.php
- resources/views/auth/passwords/email.blade.php
- resources/views/auth/passwords/reset.blade.php
- enviar un correo con un enlace para restablecer la contraseña del usuario en cuanto pulsa `¿Has olvidado tu contraseña?`
> restablecer y enviar correo para recuperar contraseña

- .idea/workspace.xml
- app/Http/Controllers/Auth/LoginController.php
- app/User.php
- database/migrations/2014_10_12_000000_create_users_table.php
- migración con nueva columna `last login` en `users`
- función que guarda el último login del usuario
> Migracion tabla user columna last login

- database/migrations/2014_10_12_000000_create_users_table.php
- migración de `users` añadiendo la columna `last_login` con `date()` -> en vez de `dateTime()`
> añadida la columna last_login en users con date()

- public/css/collapse.css
- resources/views/layouts/app.blade.php
- resources/views/posts/_cards.blade.php
- resources/views/posts/formulario_crear_post.blade.php
- resources/views/posts/formulario_editar_post.blade.php
He añadido una limitación de 3 líneas en las cards para la descripción, con un enlace '...' que cuando clickas en él se ve el resto. 
También he limitado los textarea de subida de archivos a 500 caracteres.
> Limitar overflow

- .idea/workspace.xml
- app/Http/Controllers/ProfileController.php
- app/User.php
- resources/views/layouts/app.blade.php
- resources/views/profiles/profile.blade.php
- routes/web.php
he añadido en user las funciones followers y followed que devuelven los datos de la tabla pivot
he añadido las funciones follow y unfollow al controlador del perfil
he puesto en funcionamiento los botones seguir, seguidores y seguidos
> Seguidores

- .idea/workspace.xml
- app/Http/Controllers/ProfileController.php
- resources/views/profiles/profile.blade.php
- routes/web.php
he cambiado el estilo del boton seguir añadiendo un dropdown
he añadido un boton para eliminar seguidores y seguidos
> funcion eliminar seguidores y seguidos

- .idea/workspace.xml
- resources/views/profiles/profile.blade.php
he borrado un div mal cerrado y he puesto text-dark al los enlaces
> retoque estilo perfil

- public/css/collapse.css
- resources/views/profiles/profile.blade.php
- actualización del color de los botones del perfil de usuario
> botones del perfil de usuario
